version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.1.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.1.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:7.4.3
    ports:
      - "3000:3000"
    networks:
      - loki
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

volumes:
    grafana_data: {}